#
# Module manifest for module 'PSSort'
#
# Generated by: Hannes Palmquist
#
# Generated on: 2022-11-13
#

@{
    RootModule           = 'PSSort.psm1'
    ModuleVersion        = '0.0.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    GUID                 = '3c686cec-c548-47e1-9de6-840e0110615d'
    Author               = 'Hannes Palmquist'
    CompanyName          = 'GetPS'
    Copyright            = '(c) Hannes Palmquist. All rights reserved.'
    Description          = 'This module contains alternative sort algorithms. The module was created mainly for educational purposes. Work in progress'
    RequiredModules      = @()
    FunctionsToExport    = '*'
    CmdletsToExport      = '*'
    VariablesToExport    = '*'
    AliasesToExport      = '*'
    PrivateData          = @{
        PSData = @{
            Prerelease               = ''
            Tags                     = @('PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')
            LicenseUri               = 'https://github.com/hanpq/PSSort/blob/main/LICENSE'
            ProjectUri               = 'https://getps.dev/modules/PSSort/usage_getstarted'
            IconUri                  = ''
            ReleaseNotes             = ''
            RequireLicenseAcceptance = $false
        }
    }
}


